services:
  api:
    container_name: todos-api
    build:
      args:
        user: devops
        uid: 1000
      context: api
      dockerfile: Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER:1
    ports:
      - 8008:8000
    volumes:
      - ./api:/var/www/api
      - /var/www/api/vendor

  # app:
  #   container_name: todos-app
  #   build:
  #     context: app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./app:/var/www/app
  #     - /var/www/app/node_modules
  #   env_file:
  #     - app/.env

volumes:
  api:
  app:

networks:
  local-ws:
    driver: bridge
